services:
  weboard.server:
    image: ${DOCKER_REGISTRY-}weboardserver
    build:
      context: .
      dockerfile: WeBoard.Server/Dockerfile
  mongodb:
    image: mongo:latest
    container_name: mongo_database
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: